# Generated by Django 4.0.4 on 2022-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(verbose_name=int),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.IntegerField(verbose_name=int),
        ),
    ]
